### ISSUE TITLE
Multiple lines of function arguments. Reduce of empty array with no initial value

### ISSUE THREAD

**Issue by diosby** [jeremyvii/vs-docblockr#75]
**Describe the bug**
Does not generate comments for multiple lines of function arguments.

**To Reproduce**
1. Go to the line before a function with multiple lines of arguments.
2. Type /** and Enter
4. See the error 'Reduce of empty array with no initial value' and the following comment block:
```php
    /**
     * [description]
     */
```

**Expected behavior**
It should generate a comment block.

**Code**
```php
     protected function getValueKeeper(
        PrintedSheets $pricingRule, 
        CalculationVariableKeeper $calculationVariableKeeper, 
        OptionCollection $options
    ): ?ValuesOfRunningMeter {
        return '';
    }
```

**Screenshots**
![Снимок экрана от 2020-06-04 16-35-18](https://user-images.githubusercontent.com/19969187/83763577-89233780-a681-11ea-8df2-3e4413c578af.png)

**Enviroment (please complete the following information):**
 - OS: Ubuntu 20.04
 - VS Code: 1.45.1, the extension: 1.1.2
 - Language: PHP

**Comment by jeremyvii** [comment]
Using `/**` will not work for snippets with multiple lines. You will have to select the whole function signature, open VS Code's command palette, and select the `Render from selection` command.

**Comment by jeremyvii** [comment]
While it may be inconvenient, unfortunately it's the most reliable option with the current architecture. VS Code doesn't provide a reliable API for extracting symbols so a language agnostic parser is used. The entire document would need to be consumed in order to determine the end of the function signature. This would be very complex to implement and could get resource expensive if a user has a syntax error.
